#!/usr/bin/env node

const crypto = require("crypto");
const fs = require("fs/promises");
const path = require("path");
const { detectProject } = require("./detect-project");
const { loadInstallState, mergeIntoRepo } = require("./merge-into-repo");
const {
  FAST_MODE_PROMPT_PATH,
  GENERATED_ROOTS,
  INSTALL_REPORT_PATH,
  MANIFEST_PATH,
  METADATA_DIR,
  ORCHESTRATOR_PROMPT_PATH,
  QUICK_REFERENCE_PATH,
  START_PATH,
  toPortablePath
} = require("./lib/install-paths");
const { renderTemplate } = require("./lib/render-template");

const REPO_ROOT = path.resolve(__dirname, "..");
const METADATA_TEMPLATE_FILES = [
  ["start.md", START_PATH],
  ["orchestrator-prompt.md", ORCHESTRATOR_PROMPT_PATH],
  ["fast-mode-prompt.md", FAST_MODE_PROMPT_PATH],
  ["quick-reference.md", QUICK_REFERENCE_PATH]
];

async function loadBlueprint(name) {
  const blueprintPath = path.join(REPO_ROOT, "blueprints", name, "blueprint.json");
  const raw = await fs.readFile(blueprintPath, "utf8");
  return JSON.parse(raw);
}

async function resolveBlueprintName(requestedName) {
  const directPath = path.join(REPO_ROOT, "blueprints", requestedName, "blueprint.json");
  try {
    await fs.access(directPath);
    return requestedName;
  } catch {}

  const blueprintDirs = await fs.readdir(path.join(REPO_ROOT, "blueprints"));
  for (const dir of blueprintDirs) {
    const blueprint = await loadBlueprint(dir);
    if ((blueprint.aliases || []).includes(requestedName)) {
      return blueprint.id;
    }
  }

  throw new Error(`Unknown blueprint: ${requestedName}`);
}

async function loadTemplate(group, fileName) {
  const templatePath = path.join(REPO_ROOT, "templates", group, fileName);
  return fs.readFile(templatePath, "utf8");
}

function addGeneratedHeader(content, templatePath, context) {
  if (!templatePath.endsWith(".md")) return content;

  const header = [
    "<!-- Generated by Codex Team Bootstrapper.",
    `Source: ${templatePath}.`,
    `Blueprint: ${context.blueprintName}.`,
    `Mode: ${context.installMode}. -->`
  ].join(" ");

  return `${header}\n\n${content}`;
}

function buildRenderContext(targetDir, detected, blueprint, mode) {
  const selectedAgents = blueprint.defaultAgents.join(", ");
  const availablePrompts = blueprint.include.prompts.join(", ");
  const availableWorkflows = blueprint.include.workflows.join(", ");
  const workflowEmphasis = blueprint.workflowEmphasis.join(", ");
  const businessFocus = blueprint.businessConcerns.join(", ");

  return {
    projectName: detected.projectName,
    projectType: blueprint.id,
    blueprint: blueprint.id,
    blueprintName: blueprint.id,
    stack: detected.stack,
    detectedStack: detected.stack,
    repoMode: detected.repoMode,
    packageManager: detected.packageManager,
    workflowEmphasis,
    businessFocus,
    generatedAt: new Date().toISOString(),
    installMode: mode,
    targetPath: targetDir,
    selectedAgents,
    availablePrompts,
    availableWorkflows,
    startPath: toPortablePath(START_PATH),
    orchestratorPromptPath: toPortablePath(ORCHESTRATOR_PROMPT_PATH),
    fastModePromptPath: toPortablePath(FAST_MODE_PROMPT_PATH),
    quickReferencePath: toPortablePath(QUICK_REFERENCE_PATH)
  };
}

async function buildFilePlan(blueprint, renderContext) {
  const filePlan = [];

  for (const agent of blueprint.defaultAgents) {
    const sourceTemplate = path.posix.join("templates", "agents", `${agent}.md`);
    const template = await loadTemplate("agents", `${agent}.md`);
    const rendered = renderTemplate(template, renderContext);
    filePlan.push({
      targetPath: toPortablePath(path.join(GENERATED_ROOTS.agents, `${agent}.md`)),
      content: addGeneratedHeader(rendered, sourceTemplate, renderContext),
      sourceTemplate
    });
  }

  for (const fileName of blueprint.include.docs) {
    const sourceTemplate = path.posix.join("templates", "docs", fileName);
    const template = await loadTemplate("docs", fileName);
    const rendered = renderTemplate(template, renderContext);
    filePlan.push({
      targetPath: toPortablePath(path.join(GENERATED_ROOTS.docs, fileName)),
      content: addGeneratedHeader(rendered, sourceTemplate, renderContext),
      sourceTemplate
    });
  }

  for (const fileName of blueprint.include.prompts) {
    const sourceTemplate = path.posix.join("templates", "prompts", fileName);
    const template = await loadTemplate("prompts", fileName);
    const rendered = renderTemplate(template, renderContext);
    filePlan.push({
      targetPath: toPortablePath(path.join(GENERATED_ROOTS.prompts, fileName)),
      content: addGeneratedHeader(rendered, sourceTemplate, renderContext),
      sourceTemplate
    });
  }

  for (const fileName of blueprint.include.workflows) {
    const sourceTemplate = path.posix.join("templates", "workflows", fileName);
    const template = await loadTemplate("workflows", fileName);
    const rendered = renderTemplate(template, renderContext);
    filePlan.push({
      targetPath: toPortablePath(path.join(GENERATED_ROOTS.workflows, fileName)),
      content: addGeneratedHeader(rendered, sourceTemplate, renderContext),
      sourceTemplate
    });
  }

  for (const [fileName, targetPath] of METADATA_TEMPLATE_FILES) {
    const sourceTemplate = path.posix.join("templates", "meta", fileName);
    const template = await loadTemplate("meta", fileName);
    const rendered = renderTemplate(template, renderContext);
    filePlan.push({
      targetPath: toPortablePath(targetPath),
      content: addGeneratedHeader(rendered, sourceTemplate, renderContext),
      sourceTemplate
    });
  }

  return filePlan;
}

function parseArgs(argv) {
  const parsed = { _: [] };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];

    if (!arg.startsWith("--")) {
      parsed._.push(arg);
      continue;
    }

    const [key, inlineValue] = arg.slice(2).split("=");
    if (inlineValue !== undefined) {
      parsed[key] = inlineValue;
      continue;
    }

    if (key === "dry-run") {
      parsed.dryRun = true;
      continue;
    }

    if (key === "mode") {
      parsed.mode = argv[index + 1];
      index += 1;
      continue;
    }

    if (key === "json") {
      parsed.json = true;
      continue;
    }

    parsed[key] = argv[index + 1];
    index += 1;
  }

  return parsed;
}

function formatSummary(targetDir, detected, blueprint, mode, mergeResult) {
  return [
    `targetDir: ${targetDir}`,
    `projectName: ${detected.projectName}`,
    `projectType: ${blueprint.id}`,
    `repoMode: ${detected.repoMode}`,
    `stack: ${detected.stack}`,
    `suggestedBlueprint: ${detected.blueprint}`,
    `blueprint: ${blueprint.id}`,
    `installMode: ${mode}`,
    `created: ${mergeResult.summary.createdFiles.length}`,
    `updated: ${mergeResult.summary.updatedFiles.length}`,
    `skipped: ${mergeResult.summary.skippedFiles.length}`,
    `manualReview: ${mergeResult.summary.manualReviewFiles.length}`,
    `deleted: ${mergeResult.summary.deletedFiles.length}`
  ].join("\n");
}

function formatActionLines(results) {
  return results
    .map((result) => `- ${result.action}: ${result.path}`)
    .join("\n");
}

async function ensureMetadataDir(targetDir) {
  await fs.mkdir(path.join(targetDir, METADATA_DIR), { recursive: true });
}

async function readExistingToolOwnedFile(targetDir, entry) {
  const absolutePath = path.join(targetDir, entry.path);
  try {
    const content = await fs.readFile(absolutePath, "utf8");
    return {
      path: entry.path,
      sourceTemplate: entry.sourceTemplate || null,
      checksum: createChecksum(content)
    };
  } catch {
    return null;
  }
}

function createChecksum(content) {
  return crypto.createHash("sha1").update(content).digest("hex");
}

async function buildInstallArtifacts(targetDir, detected, blueprint, renderContext, filePlan, mergeResult, previousState) {
  const plannedByPath = new Map(
    filePlan.map((item) => [
      item.targetPath,
      {
        path: item.targetPath,
        sourceTemplate: item.sourceTemplate || null,
        checksum: createChecksum(item.content)
      }
    ])
  );

  const nextOwnedFiles = [];
  const retainedPrevious = [];

  for (const result of mergeResult.results) {
    if (["created", "updated"].includes(result.action)) {
      const ownedRecord = plannedByPath.get(result.path);
      if (ownedRecord) nextOwnedFiles.push(ownedRecord);
      continue;
    }

    if (result.action === "skipped-tool-owned") {
      const plannedRecord = plannedByPath.get(result.path);
      if (plannedRecord) {
        const existingRecord = await readExistingToolOwnedFile(targetDir, plannedRecord);
        nextOwnedFiles.push(existingRecord || plannedRecord);
      }
    }
  }

  if (renderContext.installMode !== "replace") {
    for (const previousEntry of previousState.toolOwnedFiles) {
      if (plannedByPath.has(previousEntry.path)) continue;
      const existingRecord = await readExistingToolOwnedFile(targetDir, previousEntry);
      if (existingRecord) retainedPrevious.push(existingRecord);
    }
  }

  const toolOwnedFiles = dedupeOwnedFiles([...nextOwnedFiles, ...retainedPrevious]);
  const metadataFiles = [MANIFEST_PATH, INSTALL_REPORT_PATH].map((filePath) => ({
    path: filePath,
    sourceTemplate: null,
    checksum: null
  }));
  const allToolOwnedFiles = dedupeOwnedFiles([...toolOwnedFiles, ...metadataFiles]);

  const manifest = {
    generatedBy: "codex-team-bootstrapper",
    version: "0.2.0",
    targetPath: targetDir,
    projectName: renderContext.projectName,
    projectType: renderContext.projectType,
    repoMode: renderContext.repoMode,
    detectedStack: renderContext.detectedStack,
    stack: renderContext.stack,
    suggestedBlueprint: detected.blueprint,
    selectedBlueprint: blueprint.id,
    blueprint: blueprint.id,
    packageManager: renderContext.packageManager,
    installMode: renderContext.installMode,
    recommendedInstallMode: blueprint.recommendedInstallMode || "safe",
    generatedAt: renderContext.generatedAt,
    aliases: blueprint.aliases || [],
    contextNotes: blueprint.contextNotes || [],
    workflowEmphasis: blueprint.workflowEmphasis,
    businessFocus: blueprint.businessConcerns,
    defaultAgents: blueprint.defaultAgents,
    include: blueprint.include,
    instructions: blueprint.instructions,
    templateVariables: {
      projectName: renderContext.projectName,
      projectType: renderContext.projectType,
      blueprint: renderContext.blueprint,
      blueprintName: renderContext.blueprintName,
      stack: renderContext.stack,
      detectedStack: renderContext.detectedStack,
      repoMode: renderContext.repoMode,
      packageManager: renderContext.packageManager,
      workflowEmphasis: renderContext.workflowEmphasis,
      businessFocus: renderContext.businessFocus,
      generatedAt: renderContext.generatedAt,
      installMode: renderContext.installMode,
      selectedAgents: renderContext.selectedAgents,
      availablePrompts: renderContext.availablePrompts,
      availableWorkflows: renderContext.availableWorkflows,
      startPath: renderContext.startPath,
      orchestratorPromptPath: renderContext.orchestratorPromptPath,
      fastModePromptPath: renderContext.fastModePromptPath,
      quickReferencePath: renderContext.quickReferencePath
    },
    toolOwnedFiles: allToolOwnedFiles
  };

  const installReport = {
    targetPath: targetDir,
    projectName: renderContext.projectName,
    projectType: renderContext.projectType,
    repoMode: renderContext.repoMode,
    detectedStack: renderContext.detectedStack,
    stack: renderContext.stack,
    detectedSignals: detected.signals,
    suggestedBlueprint: detected.blueprint,
    selectedBlueprint: blueprint.id,
    blueprint: blueprint.id,
    installMode: renderContext.installMode,
    recommendedInstallMode: blueprint.recommendedInstallMode || "safe",
    packageManager: renderContext.packageManager,
    createdFiles: mergeResult.summary.createdFiles,
    updatedFiles: mergeResult.summary.updatedFiles,
    skippedFiles: mergeResult.summary.skippedFiles,
    conflictsAvoided: mergeResult.summary.conflictsAvoided,
    manualReviewFiles: mergeResult.summary.manualReviewFiles,
    deletedFiles: mergeResult.summary.deletedFiles,
    toolOwnedFiles: allToolOwnedFiles,
    generatedAt: renderContext.generatedAt,
    manifestPath: MANIFEST_PATH
  };

  return { manifest, installReport };
}

function dedupeOwnedFiles(entries) {
  const seen = new Map();
  for (const entry of entries) {
    seen.set(entry.path, {
      path: entry.path,
      sourceTemplate: entry.sourceTemplate || null,
      checksum: entry.checksum || null
    });
  }
  return Array.from(seen.values()).sort((left, right) => left.path.localeCompare(right.path));
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const targetDir = path.resolve(args._[0] || process.cwd());
  const detected = await detectProject(targetDir);
  const selectedBlueprint = args.blueprint
    ? await resolveBlueprintName(args.blueprint)
    : detected.blueprint;
  const mode = args.mode || "safe";
  const blueprint = await loadBlueprint(selectedBlueprint);
  const renderContext = buildRenderContext(targetDir, detected, blueprint, mode);
  const filePlan = await buildFilePlan(blueprint, renderContext);
  const mergeResult = await mergeIntoRepo(targetDir, filePlan, {
    mode,
    dryRun: args.dryRun
  });

  if (!args.dryRun) {
    await ensureMetadataDir(targetDir);
    const previousState = await loadInstallState(targetDir);
    const { manifest, installReport } = await buildInstallArtifacts(
      targetDir,
      detected,
      blueprint,
      renderContext,
      filePlan,
      mergeResult,
      previousState
    );
    await fs.writeFile(path.join(targetDir, MANIFEST_PATH), JSON.stringify(manifest, null, 2) + "\n", "utf8");
    await fs.writeFile(
      path.join(targetDir, INSTALL_REPORT_PATH),
      JSON.stringify(installReport, null, 2) + "\n",
      "utf8"
    );
  }

  if (args.json) {
    console.log(
      JSON.stringify(
        {
          targetDir,
          detected,
          blueprint,
          renderContext,
          filePlan,
          mergeResult
        },
        null,
        2
      )
    );
    return;
  }

  console.log(formatSummary(targetDir, detected, blueprint, mode, mergeResult));
  console.log("");
  console.log(formatActionLines(mergeResult.results));

  if (args.dryRun) {
    console.log("");
    console.log("Dry run only. No files were written.");
  } else {
    console.log("");
    console.log(`Updated metadata: ${MANIFEST_PATH}, ${INSTALL_REPORT_PATH}`);
    console.log(`Start here: ${START_PATH}`);
    console.log(`Paste this prompt into Codex: ${ORCHESTRATOR_PROMPT_PATH}`);
    console.log(`For small tasks, use: ${FAST_MODE_PROMPT_PATH}`);
  }
}

if (require.main === module) {
  main().catch((error) => {
    console.error(error.message);
    process.exit(1);
  });
}

module.exports = {
  buildFilePlan,
  loadBlueprint
};
