#!/usr/bin/env node

const fs = require("fs/promises");
const path = require("path");
const {
  MANIFEST_PATH,
  INSTALL_REPORT_PATH,
  START_PATH,
  ORCHESTRATOR_PROMPT_PATH,
  QUICK_REFERENCE_PATH
} = require("./lib/install-paths");

async function readIfExists(filePath) {
  try {
    return await fs.readFile(filePath, "utf8");
  } catch {
    return null;
  }
}

async function loadContext(targetDir) {
  const start = await readIfExists(path.join(targetDir, START_PATH));
  const prompt = await readIfExists(path.join(targetDir, ORCHESTRATOR_PROMPT_PATH));
  const quickReference = await readIfExists(path.join(targetDir, QUICK_REFERENCE_PATH));
  const manifestRaw = await readIfExists(path.join(targetDir, MANIFEST_PATH));
  const reportRaw = await readIfExists(path.join(targetDir, INSTALL_REPORT_PATH));

  return {
    start,
    prompt,
    quickReference,
    manifest: manifestRaw ? JSON.parse(manifestRaw) : null,
    report: reportRaw ? JSON.parse(reportRaw) : null
  };
}

function stripGeneratedHeader(content) {
  return content.replace(/^<!-- Generated by Codex Team Bootstrapper[\s\S]*?-->\n\n/, "");
}

function formatFallback(targetDir, manifest, report) {
  return [
    `Target repo: ${targetDir}`,
    `Blueprint: ${manifest?.selectedBlueprint || "unknown"}`,
    `Install mode: ${manifest?.installMode || "unknown"}`,
    `Start file: ${START_PATH}`,
    `Prompt file: ${ORCHESTRATOR_PROMPT_PATH}`,
    `Quick reference: ${QUICK_REFERENCE_PATH}`,
    `Created files last install: ${report?.createdFiles?.length || 0}`,
    `Updated files last install: ${report?.updatedFiles?.length || 0}`
  ].join("\n");
}

async function main() {
  const targetDir = path.resolve(process.argv[2] || process.cwd());
  const context = await loadContext(targetDir);

  if (!context.start) {
    console.log(formatFallback(targetDir, context.manifest, context.report));
    console.log("");
    console.log("No generated start.md found. Run bootstrap first or point this command at an installed repo.");
    return;
  }

  console.log(stripGeneratedHeader(context.start).trim());

  if (context.prompt) {
    console.log("");
    console.log("--- Recommended Orchestrator Prompt ---");
    console.log("");
    console.log(stripGeneratedHeader(context.prompt).trim());
  }

  if (context.quickReference) {
    console.log("");
    console.log("--- Quick Reference Path ---");
    console.log(QUICK_REFERENCE_PATH);
  }
}

if (require.main === module) {
  main().catch((error) => {
    console.error(error.message);
    process.exit(1);
  });
}
