#!/usr/bin/env node

const fs = require("fs/promises");
const path = require("path");
const {
  FAST_MODE_PROMPT_PATH,
  MANIFEST_PATH,
  INSTALL_REPORT_PATH,
  START_PATH,
  ORCHESTRATOR_PROMPT_PATH,
  QUICK_REFERENCE_PATH
} = require("./lib/install-paths");

async function readIfExists(filePath) {
  try {
    return await fs.readFile(filePath, "utf8");
  } catch {
    return null;
  }
}

async function loadContext(targetDir) {
  const start = await readIfExists(path.join(targetDir, START_PATH));
  const prompt = await readIfExists(path.join(targetDir, ORCHESTRATOR_PROMPT_PATH));
  const fastModePrompt = await readIfExists(path.join(targetDir, FAST_MODE_PROMPT_PATH));
  const quickReference = await readIfExists(path.join(targetDir, QUICK_REFERENCE_PATH));
  const manifestRaw = await readIfExists(path.join(targetDir, MANIFEST_PATH));
  const reportRaw = await readIfExists(path.join(targetDir, INSTALL_REPORT_PATH));

  return {
    start,
    prompt,
    fastModePrompt,
    quickReference,
    manifest: manifestRaw ? JSON.parse(manifestRaw) : null,
    report: reportRaw ? JSON.parse(reportRaw) : null
  };
}

function stripGeneratedHeader(content) {
  return content.replace(/^<!-- Generated by Codex Team Bootstrapper[\s\S]*?-->\n\n/, "");
}

function extractPromptBody(content) {
  const stripped = stripGeneratedHeader(content).trim();
  const match = stripped.match(/```text\n([\s\S]*?)\n```/);
  return match ? match[1].trim() : stripped;
}

function summarizeList(items, limit = 6) {
  if (!Array.isArray(items) || items.length === 0) return "none";
  return items.slice(0, limit).join(", ") + (items.length > limit ? ", ..." : "");
}

function formatSummary(targetDir, manifest, report) {
  const summaryLines = [
    `Project: ${manifest?.projectName || path.basename(targetDir)}`,
    `Repo mode: ${manifest?.repoMode || report?.repoMode || "unknown"}`,
    `Stack: ${manifest?.detectedStack || report?.detectedStack || "unknown"}`,
    `Blueprint: ${manifest?.selectedBlueprint || report?.selectedBlueprint || "unknown"}`,
    `Install mode: ${manifest?.installMode || report?.installMode || "unknown"}`
  ];

  const systemLines = [
    `Agents: ${summarizeList(manifest?.defaultAgents)}`,
    `Prompts: ${summarizeList(manifest?.include?.prompts)}`,
    `Workflows: ${summarizeList(manifest?.include?.workflows)}`
  ];

  return [...summaryLines, "", ...systemLines].join("\n");
}

function formatQuickUsage() {
  return [
    "Quick usage:",
    "- feature: prompts/ai-team/new-feature-request.md -> workflows/ai-team/feature-delivery.md",
    "- bugfix: prompts/ai-team/bugfix-request.md -> workflows/ai-team/bugfix-flow.md",
    "- review: agents/code-reviewer.md -> workflows/ai-team/release-readiness.md",
    `- small task: ${FAST_MODE_PROMPT_PATH}`
  ].join("\n");
}

function formatDayOneFlow() {
  return [
    "Day 1 flow:",
    `1. Open ${START_PATH}`,
    `2. Paste ${ORCHESTRATOR_PROMPT_PATH} into Codex`,
    `3. Use ${FAST_MODE_PROMPT_PATH} instead when the task is narrow and self-contained`,
    `4. Use ${QUICK_REFERENCE_PATH} for the workflow path`,
    "5. Ask for subagents only when the work can be split cleanly"
  ].join("\n");
}

async function main() {
  const targetDir = path.resolve(process.argv[2] || process.cwd());
  const context = await loadContext(targetDir);

  if (!context.start) {
    console.log(formatSummary(targetDir, context.manifest, context.report));
    console.log("");
    console.log("No generated start.md found. Run bootstrap first or point this command at an installed repo.");
    return;
  }

  const promptBody = context.prompt ? extractPromptBody(context.prompt) : "";

  console.log(formatSummary(targetDir, context.manifest, context.report));
  console.log("");
  console.log("Start here:");
  console.log(`- open: ${START_PATH}`);
  console.log(`- paste: ${ORCHESTRATOR_PROMPT_PATH}`);
  console.log(`- fast mode: ${FAST_MODE_PROMPT_PATH}`);
  console.log(`- quick ref: ${QUICK_REFERENCE_PATH}`);
  console.log("");
  console.log("Recommended next step:");
  console.log("Copy this into Codex:");
  console.log(promptBody);
  console.log("");
  console.log(formatQuickUsage());
  console.log("");
  console.log(formatDayOneFlow());
  console.log("");
  console.log("Pointers:");
  console.log(`- ${START_PATH}`);
  console.log(`- ${ORCHESTRATOR_PROMPT_PATH}`);
  console.log(`- ${FAST_MODE_PROMPT_PATH}`);
  console.log(`- ${QUICK_REFERENCE_PATH}`);
  console.log("- installed summary is printed above");
}

if (require.main === module) {
  main().catch((error) => {
    console.error(error.message);
    process.exit(1);
  });
}
